// 115 年題庫參考解；以可編譯成積木的小型記法撰寫（見 blockly-compiler.cjs）。
const S={};
S[1]=`let n=read();let total=0;for(let i=0;i<n;i++){total+=read();}print(cat(total," ",floor(total/n)));`;
S[2]=`let child=read();let adult=read();print(child*250+adult*350);`;
S[3]=`let n=read();let k=read();print(ceil(n/k));`;
S[4]=`let t=read();if(t<=22){print("冷泉");}else{if(t>=40){print("溫泉");}else{print("溫水");}}`;
S[5]=`let n=read();let best=0;let who=0;for(let i=0;i<n;i++){let x=read();if(i==0 || x<best){best=x;who=i+1;}}print(cat(who," ",best));`;
S[6]=`let n=read();let total=0;for(let i=0;i<n;i++){total+=read();}let money=read();if(money>=total){print(money-total);}else{print("錢不夠");}`;
S[7]=`let n=read();let k=read();let cars=ceil(n/k);print(cat(cars," ",n-(cars-1)*k));`;
S[8]=`let a=read();let b=read();print(cat(a*b," ",(a+b)*2));`;
S[9]=`let n=read();let c=zeros(5);for(let i=0;i<n;i++){let x=read();c[x]=c[x]+1;}let best=max(c[1],c[2],c[3],c[4]);let tied=0;let answer=0;for(let i=1;i<=4;i++){if(c[i]==best){tied++;answer=i;}}if(tied==1){print(answer);}else{print("平手");}`;
S[10]=`let m=read();let k=read();print(cat(floor((k-1)/m)+1," ",(k-1)%m+1));`;
S[11]=`let h=read();let s=read();let m=read();let past=(h-9)*60+s;print((m-past%m)%m);`;
S[12]=`let n=read();let count=0;let best=0;for(let i=0;i<n;i++){let x=read();if(x>=100){count++;}best=max(best,x);}print(cat(count," ",best));`;
S[13]=`let n=read();let a=[];for(let i=0;i<n;i++){push(a,read());}let e=read();let done=0;let stop=0;for(let i=0;i<n;i++){if(stop==0){if(e>=a[i]){e=e-a[i];done++;}else{stop=1;}}}if(done==n){print("全程完成");}else{print(done);}`;
S[14]=`let n=read();let big=floor(n/12);let rest=n%12;print(cat(big," ",floor(rest/5)," ",rest%5));`;
S[15]=`let p=read();let n=read();let total=p*n;if(n>=10){total=floor(total*8/10);}else{if(n>=5){total=floor(total*9/10);}}print(total);`;
S[16]=`let l=read();let d=read();print(cat(floor(d/l)," ",d%l));`;
S[17]=`let n=read();let small=0;let mid=0;let big=0;for(let i=0;i<n;i++){let w=read();if(w<1000){small++;}else{if(w<3000){mid++;}else{big++;}}}print(cat(small," ",mid," ",big));`;
S[18]=`let n=read();let a=[];for(let i=0;i<n;i++){push(a,read());}let s=sort(a,1);print(cat(s[0]," ",s[1]," ",s[2]));`;
S[19]=`let s=word();let letters=["A","B","C","D","E"];let seen=zeros(5);let got=0;let answer=0;for(let i=0;i<strlen(s);i++){let p=index(letters,char(s,i));if(seen[p]==0){seen[p]=1;got++;if(got==5){answer=i+1;}}}if(answer==0){print("未集齊");}else{print(answer);}`;
S[20]=`let n=read();let a=[];for(let i=0;i<n;i++){push(a,read());}let k=read();let best=-1;let start=1;for(let i=0;i<=n-k;i++){let s=0;for(let j=i;j<i+k;j++){s+=a[j];}if(s>best){best=s;start=i+1;}}print(cat(best," ",start));`;
S[21]=`let n=read();let a=[];for(let i=0;i<n;i++){push(a,read());}let c=read();let wait=0;let most=0;for(let i=0;i<n;i++){wait+=a[i];most=max(most,wait);wait=wait-min(wait,c);}print(cat(wait," ",most));`;
S[22]=`let s=word();let letters=["A","E","I","O","U"];let c=zeros(5);for(let i=0;i<strlen(s);i++){let p=index(letters,char(s,i));if(p>=0){c[p]=c[p]+1;}}print(cat(c[0]," ",c[1]," ",c[2]," ",c[3]," ",c[4]));`;
S[23]=`let n=read();let x=0;let y=0;let d=0;let dx=[0,1,0,-1];let dy=[1,0,-1,0];for(let i=0;i<n;i++){let c=word();if(c=="F"){x+=dx[d];y+=dy[d];}else{if(c=="R"){d=(d+1)%4;}else{d=(d+3)%4;}}}print(cat("(",x,",",y,")"));`;
S[24]=`let n=read();let a=[];for(let i=0;i<n;i++){push(a,read());}let total=sum(a);let left=0;let best=1000000000;let answer=0;for(let i=0;i<n-1;i++){left+=a[i];let diff=abs(total-2*left);if(diff<best){best=diff;answer=left;}}print(cat(min(answer,total-answer)," ",max(answer,total-answer)));`;
S[25]=`let n=read();let keys=[];for(let i=0;i<n;i++){let s=read();let e=read();push(keys,e*1000+s);}let sorted=sort(keys,1);let count=0;let last=-1000;for(let i=0;i<n;i++){let e=floor(sorted[i]/1000);let s=sorted[i]%1000;if(s>=last){count++;last=e;}}print(count);`;
S[26]=`let adult=read();let child=read();let senior=read();print(adult*600+child*300+senior*0);`;
S[27]=`let n=read();let hi=0;let lo=0;for(let i=0;i<n;i++){let x=read();if(i==0){hi=x;lo=x;}else{hi=max(hi,x);lo=min(lo,x);}}print(cat(hi," ",lo," ",hi-lo));`;
S[28]=`let d=read();let l=read();let r=d/2;print(floor(3.14*r*r*l));`;
S[29]=`let n=read();let total=0;let best=0;for(let i=0;i<n;i++){let x=read();total+=x;best=max(best,x);}print(cat(total," ",best));`;
S[30]=`let a=[];for(let i=0;i<5;i++){push(a,read());}let s=sort(a,1);print(floor((s[1]+s[2]+s[3])/3));`;
S[31]=`let p=read();let q=read();let n=read();let total=0;for(let i=0;i<n;i++){let holiday=read();if(holiday==1){total+=q;}else{total+=p;}}if(n>=3){total=floor(total*9/10);}print(total);`;
S[32]=`let s=word();let total=0;for(let i=0;i<5;i++){total+=number(char(s,i))*(i+1);}if(total%7==0){print("yes");}else{print("no");}`;
S[33]=`let n=read();let a=[];for(let i=0;i<n;i++){push(a,read());}let hi=a[0];for(let i=0;i<n;i++){hi=max(hi,a[i]);}let second=-1;for(let i=0;i<n;i++){if(a[i]<hi){second=max(second,a[i]);}}if(second<0){print(cat(hi," ","無"));}else{print(cat(hi," ",second));}`;
S[34]=`let n=read();let k=read();let m=read();print(k*m%n+1);`;
S[35]=`let n=read();let total=0;for(let i=0;i<n;i++){let age=read();if(age>=65){total+=50;}else{if(age>=19){total+=100;}else{if(age>=6){total+=50;}}}}print(total);`;
S[36]=`let n=read();let x=read();let lo=1;let hi=n;let out=[];let count=0;let done=0;while(done==0){let mid=floor((lo+hi)/2);push(out,mid);count++;if(mid==x){done=1;}else{if(mid<x){lo=mid+1;}else{hi=mid-1;}}}print(join(out));print(count);`;
S[37]=`let n=read();let names=[];let vals=[];for(let i=0;i<n;i++){push(names,word());push(vals,read());}let k=read();let out=[];for(let r=0;r<k;r++){let bestI=0;let bestV=-1;for(let i=0;i<n;i++){if(vals[i]>bestV){bestV=vals[i];bestI=i;}}push(out,names[bestI]);vals[bestI]=-1;}print(join(out));`;
S[38]=`let n=read();let state="STOP";let count=0;for(let i=0;i<n;i++){let c=word();if(c=="G"){if(state=="STOP"){state="RUN";count++;}}else{if(c=="M"){if(state=="STOP" || state=="RUN"){state="FIX";}}else{if(c=="S"){if(state=="RUN"){state="STOP";}}else{if(state=="FIX"){state="STOP";}}}}}print(cat(state," ",count));`;
S[39]=`let b=read();let m=read();let price=[];let stock=[];for(let i=0;i<m;i++){push(price,read());}for(let i=0;i<m;i++){push(stock,read());}for(let i=0;i<m;i++){for(let j=i+1;j<m;j++){if(price[j]<price[i]){let t=price[i];price[i]=price[j];price[j]=t;t=stock[i];stock[i]=stock[j];stock[j]=t;}}}let count=0;for(let i=0;i<m;i++){let take=min(stock[i],floor(b/price[i]));count+=take;b=b-take*price[i];}print(count);`;
S[40]=`let n=read();let x=10;let y=10;for(let i=0;i<n;i++){let cmd=word();let dir=char(cmd,0);let v=0;for(let j=1;j<strlen(cmd);j++){v=v*10+number(char(cmd,j));}let nx=x;let ny=y;if(dir=="N"){ny=y+v;}else{if(dir=="S"){ny=y-v;}else{if(dir=="E"){nx=x+v;}else{nx=x-v;}}}if(nx>=0 && nx<=20 && ny>=0 && ny<=20){x=nx;y=ny;}}print(cat("(",x,",",y,")"," ",abs(x-10)+abs(y-10)));`;
S[41]=`let n=read();let result=1;for(let i=0;i<n;i++){let t=read();let a=result;let b=t;while(b!=0){let r=a%b;a=b;b=r;}result=result*t/a;}print(result);`;
S[42]=`let n=read();let h=read();let count=0;let best=0;let alert=0;for(let i=0;i<n;i++){let x=read();if(x>=h){if(alert==0){count++;}alert=1;}else{alert=0;}best=max(best,x);}print(cat(count," ",best));`;
S[43]=`let n=read();let names=[];let sums=[];for(let i=0;i<n;i++){let name=word();let v=read();let p=index(names,name);if(p<0){push(names,name);push(sums,v);}else{sums[p]=sums[p]+v;}}let out=[];for(let i=0;i<len(names);i++){push(out,names[i]);push(out,sums[i]);}print(join(out));`;
S[44]=`let n=read();let a=[];for(let i=0;i<n;i++){push(a,read());}let swaps=0;for(let i=0;i<n;i++){for(let j=0;j<n-1;j++){if(a[j]>a[j+1]){let t=a[j];a[j]=a[j+1];a[j+1]=t;swaps++;}}}let out=[];for(let i=0;i<n;i++){push(out,a[i]);}push(out,swaps);print(join(out));`;
S[45]=`let n=read();let h=[];for(let i=0;i<n;i++){push(h,read());}let dp=zeros(n);dp[1]=abs(h[1]-h[0]);for(let i=2;i<n;i++){dp[i]=min(dp[i-1]+abs(h[i]-h[i-1]),dp[i-2]+abs(h[i]-h[i-2])+2);}print(dp[n-1]);`;
S[46]=`let n=read();let m=read();let g=[];for(let i=0;i<n*m;i++){push(g,read());}let best=-1;let br=1;let bc=1;for(let r=0;r<n-1;r++){for(let c=0;c<m-1;c++){let s=g[r*m+c]+g[r*m+c+1]+g[(r+1)*m+c]+g[(r+1)*m+c+1];if(s>best){best=s;br=r+1;bc=c+1;}}}print(cat(best," ",br," ",bc));`;
S[47]=`let n=read();let starts=[];let ends=[];let keys=[];for(let i=0;i<n;i++){let s=read();let e=read();push(starts,s);push(ends,e);push(keys,e*100+i);}let sorted=sort(keys,1);let last=-1000;let out=[];for(let i=0;i<n;i++){let idx=sorted[i]%100;if(starts[idx]>=last){push(out,idx+1);last=ends[idx];}}print(len(out));print(join(out));`;
S[48]=`let n=read();let pre=zeros(n);for(let i=1;i<n;i++){pre[i]=pre[i-1]+read();}let q=read();let out=[];for(let i=0;i<q;i++){let a=read();let b=read();push(out,abs(pre[a-1]-pre[b-1]));}print(join(out));`;
S[49]=`let m=read();let n=read();let score=[];for(let i=0;i<n;i++){push(score,read());}let chosen=zeros(n);let taken=0;let done=0;while(done==0){let best=-1;for(let i=0;i<n;i++){if(chosen[i]==0 && score[i]>best){best=score[i];}}if(best<0){done=1;}else{let group=0;for(let i=0;i<n;i++){if(chosen[i]==0 && score[i]==best){group++;}}if(taken+group<=m){for(let i=0;i<n;i++){if(chosen[i]==0 && score[i]==best){chosen[i]=1;}}taken+=group;}else{done=1;}}}let out=[];for(let i=0;i<n;i++){if(chosen[i]==1){push(out,i+1);}}if(len(out)==0){print(0);}else{print(join(out));}`;
S[50]=`let f=read();let n=read();let cost=[];let gain=[];for(let i=0;i<n;i++){push(cost,read());push(gain,read());}let best=0;let total=2**n;for(let mask=0;mask<total;mask++){let c=0;let g=0;for(let i=0;i<n;i++){if(floor(mask/(2**i))%2==1){c+=cost[i];g+=gain[i];}}if(c<=f){best=max(best,g);}}print(best);`;
S[51]=`let p=read();let m=read();print(m-p);`;
S[52]=`let y=read();if(y%400==0){print("閏年");}else{if(y%100==0){print("平年");}else{if(y%4==0){print("閏年");}else{print("平年");}}}`;
S[53]=`let n=read();let hi=0;let lo=0;for(let i=0;i<n;i++){let x=read();if(i==0){hi=x;lo=x;}else{hi=max(hi,x);lo=min(lo,x);}}print(cat(hi," ",lo," ",hi-lo));`;
S[54]=`let n=read();let rev=0;while(n>0){rev=rev*10+n%10;n=floor(n/10);}print(rev);`;
S[55]=`let n=read();let count=0;for(let i=1;i<=n;i++){let ok=1;if(i%7==0){ok=0;}let t=i;while(t>0){if(t%10==7){ok=0;}t=floor(t/10);}if(ok==1){count++;}}print(count);`;
S[56]=`let n=read();let a=[];for(let i=0;i<n;i++){push(a,read());}let x=read();let higher=0;for(let i=0;i<n;i++){if(a[i]>x){higher++;}}print(higher+1);`;
S[57]=`let n=read();let count=0;let last=0;for(let x=2;x<=n;x++){let prime=1;for(let d=2;d<=floor(sqrt(x));d++){if(x%d==0){prime=0;}}if(prime==1){count++;last=x;}}print(cat(count," ",last));`;
S[58]=`let n=read();let a=1;let b=1;for(let i=2;i<=n;i++){let next=a+b;a=b;b=next;}print(b);`;
S[59]=`let n=read();let best=0;let run=0;for(let i=0;i<n;i++){let x=read();if(x==1){run++;best=max(best,run);}else{run=0;}}print(best);`;
S[60]=`let n=read();let best=-100000;let cur=-100000;for(let i=0;i<n;i++){let x=read();cur=max(cur+x,x);best=max(best,cur);}print(best);`;
S[61]=`let a=read();let b=read();let c=read();if(a+b>c && a+c>b && b+c>a){if(a==b && b==c){print("等邊三角形");}else{if(a==b || b==c || a==c){print("等腰三角形");}else{print("一般三角形");}}}else{print("不是三角形");}`;
S[62]=`let d=read();let fee=0;if(d>330){fee=120*2+210*3+(d-330)*5;}else{if(d>120){fee=120*2+(d-120)*3;}else{fee=d*2;}}print(fee);`;
S[63]=`let n=read();let s=0;while(n>0){s+=n%10;n=floor(n/10);}let root=s;while(root>9){let t=0;let x=root;while(x>0){t+=x%10;x=floor(x/10);}root=t;}print(cat(s," ",root));`;
S[64]=`let n=read();let out="";if(n==0){out="0";}while(n>0){out=cat(n%2,out);n=floor(n/2);}print(out);`;
S[65]=`let n=read();let g=0;let l=1;for(let i=0;i<n;i++){let t=read();let a=g;let b=t;while(b!=0){let r=a%b;a=b;b=r;}g=a;let a2=l;let b2=t;while(b2!=0){let r2=a2%b2;a2=b2;b2=r2;}l=l*t/a2;}print(cat(g," ",l));`;
S[66]=`let n=read();let k=read();let c=zeros(k+1);for(let i=0;i<n;i++){let v=read();c[v]=c[v]+1;}let best=-1;let who=1;for(let i=1;i<=k;i++){if(c[i]>best){best=c[i];who=i;}}print(cat(who," ",best));`;
S[67]=`let n=read();let g=[];for(let i=0;i<n*n;i++){push(g,read());}let d1=0;let d2=0;for(let i=0;i<n;i++){d1+=g[i*n+i];d2+=g[i*n+(n-1-i)];}print(cat(d1," ",d2));`;
S[68]=`let n=read();let k=read();let alive=[];for(let i=0;i<n;i++){push(alive,i+1);}let pos=0;while(len(alive)>1){pos=(pos+k-1)%len(alive);let out=[];for(let i=0;i<len(alive);i++){if(i!=pos){push(out,alive[i]);}}alive=out;if(pos>=len(alive)){pos=0;}}print(alive[0]);`;
S[69]=`let k=read();let coin=[];for(let i=0;i<k;i++){push(coin,read());}let m=read();let dp=zeros(m+1);for(let i=1;i<=m;i++){dp[i]=100000;}for(let i=1;i<=m;i++){for(let j=0;j<k;j++){if(coin[j]<=i){dp[i]=min(dp[i],dp[i-coin[j]]+1);}}}if(dp[m]>=100000){print(-1);}else{print(dp[m]);}`;
S[70]=`let r=read();let c=read();let grid=[];for(let i=0;i<r;i++){push(grid,word());}let dist=zeros(r*c);for(let i=0;i<r*c;i++){dist[i]=-1;}dist[0]=0;let queue=[0];let head=0;while(head<len(queue)){let cur=queue[head];head++;let cr=floor(cur/c);let cc=cur%c;let dr=[-1,1,0,0];let dc=[0,0,-1,1];for(let d=0;d<4;d++){let nr=cr+dr[d];let nc=cc+dc[d];if(nr>=0 && nr<r && nc>=0 && nc<c){if(char(grid[nr],nc)=="." && dist[nr*c+nc]<0){dist[nr*c+nc]=dist[cur]+1;push(queue,nr*c+nc);}}}}print(dist[r*c-1]);`;
module.exports=S;
